name: CD

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "false"

      - name: Get version from file
        run: |
          VERSION_FILE="$/navix/_version.py"
          NAVIX_VERSION="$(cat navix/_version.py | grep '__version__ = ' |  cut -d'=' -f2 | sed 's,\",,g' | sed "s,\',,g" | sed 's, ,,g')"
          echo "Current version is:"
          echo "$NAVIX_VERSION"

      - name: Create and push tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ env.NAVIX_VERSION }}

      - name: Create Release
        uses: ncipollo/release-action@v1.3.1
        with:
          tag: ${{ env.NAVIX_VERSION }}
          name: "NAVIX release v${{ env.NAVIX_VERSION }}"
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install pypa/build
        run: |
          python -m pip install build

      - name: Build wheel and sdist
        run: |
          python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          password: ${{ secrets.PYPI_API_KEY }}
